site_name: Seabird Innovation

nav:
  - Home: index.md
  - Tech Radar: "/tech-radar"
  - GenAI: genai-usecases.md

theme:
  name: material
  palette:
    primary: custom

extra_css:
  - stylesheets/extra.css
